name = "RomuRandoms"
uuid = "8871c1a0-d24e-4550-ade9-ece2e77790e8"
authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"]
version = "0.1.0"
license = "MIT"
repo = "https://github.com/JeffreySarnoff/RomuRandoms.jl"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
Polynomials = "0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
Terms
